#!/usr/bin/env bash

#  execute the test -- you would most likely execute on submitted file
#  for example: cppcheck ../student_file.h <options>

# src code references
source='cppcheck.cpp
  ../redirect_io.h 
  ../p1.h ../p1.cpp
  ../p2.h ../p2.cpp
  ../p3.h ../p3.cpp
  ../p4.h ../p4.cpp
  ../p5.h ../p5.cpp
  ../p6.h ../p6.cpp
  ../p7.h ../p7.cpp
  ../p8.h ../p8.cpp
  ../p9.h ../p9.cpp
  '

cppcheck ${source} -x c++ --enable=all --verbose --error-exitcode=1 --suppressions-list=suppressions.txt